# Generated by Django 4.2 on 2023-05-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_de_nacimiento', models.DateField()),
                ('altura', models.FloatField()),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
