# Generated by Django 4.2 on 2023-06-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialesentregados',
            name='soldador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smartwelding.soldador'),
            preserve_default=False,
        ),
    ]
