# Generated by Django 4.2 on 2023-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialesentregados',
            name='nommbreInspector',
            field=models.CharField(max_length=50),
        ),
    ]
