# Generated by Django 4.2 on 2023-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0002_empresa_rename_soldadores_soldador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.CharField(max_length=4)),
                ('nominal1', models.FloatField()),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='junta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoJunta', models.CharField(max_length=20)),
                ('linea', models.CharField(max_length=100)),
                ('especificacion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=40)),
                ('shedule', models.CharField(max_length=4)),
                ('tipoExtremo', models.CharField(max_length=15)),
                ('tipoMaterial', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('nominal', models.CharField(max_length=4)),
                ('nominal1', models.FloatField()),
                ('factorPulgadasDiametrales', models.FloatField()),
                ('pulgadasDiametrales', models.FloatField()),
                ('pulgadasContabilizadas', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('shedule', models.CharField(max_length=4)),
                ('tipoExtremo', models.CharField(max_length=15)),
                ('tipoMaterial', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesConsumidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoC', models.CharField(max_length=40)),
                ('sheduleC', models.CharField(max_length=4)),
                ('tipoExtremoC', models.CharField(max_length=15)),
                ('tipoMaterialC', models.CharField(max_length=30)),
                ('materialC', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesEntregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoE', models.CharField(max_length=40)),
                ('sheduleE', models.CharField(max_length=4)),
                ('tipoExtremoE', models.CharField(max_length=15)),
                ('tipoMaterialE', models.CharField(max_length=30)),
                ('materialE', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaHidrostatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInspector', models.CharField(verbose_name=25)),
                ('apellidoInspector', models.CharField(verbose_name=25)),
                ('fecha', models.DateField()),
                ('nombreObra', models.CharField(verbose_name=30)),
                ('lugarObra', models.CharField(verbose_name=30)),
                ('material', models.CharField(verbose_name=25)),
                ('tipo', models.CharField(verbose_name=30)),
                ('clase', models.CharField(verbose_name=30)),
                ('diametro', models.CharField(verbose_name=30)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulgadasDiametrales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorPulgadasDiametrales', models.FloatField()),
                ('pulgadasDiametrales', models.FloatField()),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
