# Generated by Django 4.2 on 2023-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0002_alter_materialesentregados_nommbreinspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialesentregados',
            name='apellidoInspector',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materialesentregados',
            name='apellidoSoldador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materialesentregados',
            name='nombreSoldador',
            field=models.CharField(max_length=50),
        ),
    ]
