# Generated by Django 4.2 on 2023-06-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0003_cliente_diametros_especificacion_junta_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='accionesCorrectivas',
            field=models.CharField(default='Acción correctiva', verbose_name=200),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='alKm',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='capacidadBomba',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='capacidadManometros',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='descripcionFuga',
            field=models.CharField(default='Descripcion fuga ', verbose_name=200),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='dictamen',
            field=models.CharField(default='Dictamen', verbose_name=200),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm1',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm2',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm3',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm4',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugarMayores',
            field=models.CharField(default='Indique fuga', verbose_name=200),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='longitud',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='perdidasPermisibles',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='presionPrueba',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='presionesAlcanzadas',
            field=models.CharField(default='Indique presion', verbose_name=200),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='temperaturaAmbiente',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='tramoKm',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='uniones',
            field=models.IntegerField(default=1),
        ),
    ]
