# Generated by Django 4.2 on 2023-06-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0003_alter_materialesentregados_apellidoinspector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialesentregados',
            name='soldador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartwelding.soldador'),
        ),
    ]
