# Generated by Django 4.2 on 2023-05-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0003_cliente_diametros_especificacion_junta_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='accionesCorrectivas',
            field=models.CharField(default='', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='alKm',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='capacidadBomba',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='capacidadManometros',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='descripcionFuga',
            field=models.CharField(default='', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='dictamen',
            field=models.CharField(default='', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm1',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm2',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm3',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugaDetectadakm4',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='fugarMayores',
            field=models.CharField(default='', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='longitud',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='perdidasPermisibles',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='presionPrueba',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='presionesAlcanzadas',
            field=models.CharField(default='', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='temperaturaAmbiente',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='tramoKm',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebahidrostatica',
            name='uniones',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
