# Generated by Django 4.2 on 2023-06-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0004_pruebahidrostatica_accionescorrectivas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(verbose_name=50)),
                ('lugar', models.CharField(verbose_name=40)),
            ],
        ),
    ]
