# Generated by Django 4.2 on 2023-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0005_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diametros',
            name='nominal',
            field=models.CharField(max_length=8),
        ),
    ]
