# Generated by Django 4.2 on 2023-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0006_alter_diametros_nominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialesentregados',
            name='coladaE',
            field=models.CharField(default='00000000', max_length=10),
        ),
    ]
