# Generated by Django 4.2 on 2023-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0007_materialesentregados_coladae'),
    ]

    operations = [
        migrations.CreateModel(
            name='juntaAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(default='Falta la linea', max_length=100)),
                ('especificacion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=40)),
                ('shedule', models.CharField(max_length=4)),
                ('tipoExtremo', models.CharField(max_length=15)),
                ('tipoMaterial', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('nominal', models.CharField(max_length=4)),
                ('nominal1', models.FloatField()),
                ('factorPulgadasDiametrales', models.FloatField()),
                ('pulgadasDiametrales', models.FloatField()),
                ('pulgadasContabilizadas', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Normal', max_length=25),
        ),
    ]
