# Generated by Django 4.2 on 2023-06-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0008_juntaaprobada_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='juntaRechazada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(default='Falta la linea', max_length=100)),
                ('especificacion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=40)),
                ('shedule', models.CharField(max_length=4)),
                ('tipoExtremo', models.CharField(max_length=15)),
                ('tipoMaterial', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('nominal', models.CharField(max_length=4)),
                ('nominal1', models.FloatField()),
                ('factorPulgadasDiametrales', models.FloatField()),
                ('pulgadasDiametrales', models.FloatField()),
                ('pulgadasContabilizadas', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
