# Generated by Django 4.2 on 2023-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0009_inspector_juntarechazada'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='colada',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AddField(
            model_name='materialesconsumidos',
            name='coladaC',
            field=models.CharField(default='00000000', max_length=10),
        ),
    ]
