# Generated by Django 4.2 on 2023-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0009_inspector_juntarechazada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
