# Generated by Django 4.2 on 2023-06-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0010_materiales_colada_materialesconsumidos_coladac'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialesentregados',
            name='apellidoInspector',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materialesentregados',
            name='apellidoSoldador',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materialesentregados',
            name='nombreInspector',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materialesentregados',
            name='nombreProyecto',
            field=models.CharField(default='', verbose_name=50),
        ),
        migrations.AddField(
            model_name='materialesentregados',
            name='nombreSoldador',
            field=models.CharField(default='', max_length=50),
        ),
    ]
