# Generated by Django 4.2 on 2023-06-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0011_materialesentregados_apellidoinspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialesentregados',
            name='inspector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smartwelding.inspector'),
            preserve_default=False,
        ),
    ]
