# Generated by Django 4.2 on 2023-06-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0010_alter_inspector_telefono2'),
        ('smartwelding', '0012_materialesentregados_inspector'),
    ]

    operations = [
    ]
