# Generated by Django 4.2 on 2023-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0013_merge_20230606_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='telefono2',
            field=models.CharField(max_length=20),
        ),
    ]
