# Generated by Django 4.2 on 2023-06-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0014_alter_inspector_telefono2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialesentregados',
            name='inspector',
        ),
    ]
