# Generated by Django 4.2 on 2023-06-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartwelding', '0015_remove_materialesentregados_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldador',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='soldador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='soldador',
            name='fecha_de_nacimiento',
        ),
    ]
